version: 3.0
services:
  web:
    build:
      context: ./Webapp
      dockerfile: ./Webapp/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./Webapp:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf